# Generated by Django 6.0 on 2025-12-20 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Component Name')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('cores', models.IntegerField(default=1, verbose_name='CPU Cores')),
                ('is_hyperthreaded', models.BooleanField(default=False, verbose_name='Hyper-Threaded')),
                ('threads', models.IntegerField(blank=True, null=True, verbose_name='CPU Threads')),
                ('clock_speed_mhz', models.IntegerField(verbose_name='Clock Speed (MHz)')),
                ('integrated_graphics', models.BooleanField(default=False, verbose_name='Integrated Graphics')),
                ('socket_type', models.CharField(blank=True, choices=[('SOCKET_1', 'Socket 1 (386)'), ('SOCKET_2', 'Socket 2 (386)'), ('SOCKET_3', 'Socket 3 (486)'), ('SOCKET_4', 'Socket 4 (Pentium)'), ('SOCKET_5', 'Socket 5 (Pentium)'), ('SOCKET_7', 'Socket 7 / Super Socket 7'), ('SLOT_1', 'Slot 1'), ('SLOT_A', 'Slot A'), ('SOCKET_370', 'Socket 370'), ('SOCKET_423', 'Socket 423'), ('SOCKET_478', 'Socket 478'), ('SOCKET_A', 'Socket A (462)'), ('SOCKET_754', 'Socket 754'), ('SOCKET_939', 'Socket 939'), ('SOCKET_AM2', 'Socket AM2'), ('SOCKET_AM2+', 'Socket AM2+'), ('SOCKET_AM3', 'Socket AM3'), ('LGA_775', 'LGA 775'), ('LGA_1156', 'LGA 1156'), ('LGA_1366', 'LGA 1366'), ('OTHER', 'Other / Proprietary')], default='SOCKET_1', max_length=50, verbose_name='Socket Type')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('ram_size_mb', models.IntegerField(verbose_name='RAM Size (MB)')),
                ('memory_type', models.CharField(choices=[('FPM', 'Fast Page Mode'), ('EDO', 'EDO DRAM'), ('SDR', 'SDR SDRAM'), ('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('RDRAM', 'RDRAM (Rambus)'), ('SO_DIMM', 'SO-DIMM (generic)'), ('OTHER', 'Other')], default='FPM', max_length=50, verbose_name='Memory Type')),
                ('speed_mhz', models.IntegerField(blank=True, null=True, verbose_name='RAM Speed (MHz)')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
    ]
