# Generated by Django 6.0 on 2025-12-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('vram_mb', models.IntegerField(verbose_name='VRAM Size (MB)')),
                ('chipset', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chipset Name')),
                ('interface', models.CharField(choices=[('ISA_8', 'ISA (8-bit)'), ('ISA_16', 'ISA (16-bit)'), ('VLB', 'VESA Local Bus (VLB)'), ('PCI', 'PCI'), ('PCI_X', 'PCI-X'), ('AGP_1X', 'AGP 1×'), ('AGP_2X', 'AGP 2×'), ('AGP_4X', 'AGP 4×'), ('AGP_8X', 'AGP 8×'), ('PCIE_1', 'PCI Express 1.x'), ('PCIE_2', 'PCI Express 2.x'), ('PCIE_3', 'PCI Express 3.x'), ('PCIE_4', 'PCI Express 4.x'), ('PCMCIA', 'PCMCIA / PC Card'), ('EXPRESSCARD', 'ExpressCard'), ('MCA', 'Micro Channel Architecture (IBM)'), ('EISA', 'EISA'), ('OTHER', 'Other / Proprietary')], max_length=50, verbose_name='Interface Name')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='RemovableStorageDrive',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('drive_type', models.CharField(choices=[('FLOPPY_525', '5.25" Floppy'), ('FLOPPY_325', '3.5" Floppy'), ('LS120', 'LS-120'), ('CD_ROM', 'CD-ROM'), ('CD_R', 'CD-R'), ('CD_RW', 'CD-RW'), ('DVD_ROM', 'DVD-ROM'), ('DVD_R', 'DVD-R'), ('DVD_RW', 'DVD-RW'), ('DVD_RAM', 'DVD-RAM'), ('DVD+R', 'DVD+R'), ('DVD+RW', 'DVD+RW'), ('BD_ROM', 'Blu-ray ROM'), ('BD_R', 'Blu-ray R'), ('BD_RE', 'Blu-ray RE'), ('OTHER', 'Other')], max_length=50, verbose_name='Drive Type')),
                ('interface', models.CharField(choices=[('ST506', 'ST-506 / MFM / RLL'), ('FLOPPY', 'Floppy'), ('IDE', 'IDE / PATA'), ('EIDE', 'EIDE'), ('ATA33', 'ATA-33'), ('ATA66', 'ATA-66'), ('ATA100', 'ATA-100'), ('ATA133', 'ATA-133'), ('SCSI_1', 'SCSI-1'), ('SCSI_2', 'SCSI-2'), ('ULTRA_SCSI', 'Ultra SCSI'), ('U160', 'Ultra160'), ('U320', 'Ultra320'), ('SATA_1', 'SATA I (1.5 Gbps)'), ('SATA_2', 'SATA II (3 Gbps)'), ('SATA_3', 'SATA III (6 Gbps)'), ('NVME', 'NVMe (PCIe)'), ('USB', 'USB'), ('FIREWIRE', 'FireWire (IEEE 1394)'), ('OTHER', 'Other')], max_length=50, verbose_name='Interface Name')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='StorageDrive',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('capacity_mb', models.IntegerField(verbose_name='Storage Drive Capacity (MB)')),
                ('interface', models.CharField(choices=[('ST506', 'ST-506 / MFM / RLL'), ('FLOPPY', 'Floppy'), ('IDE', 'IDE / PATA'), ('EIDE', 'EIDE'), ('ATA33', 'ATA-33'), ('ATA66', 'ATA-66'), ('ATA100', 'ATA-100'), ('ATA133', 'ATA-133'), ('SCSI_1', 'SCSI-1'), ('SCSI_2', 'SCSI-2'), ('ULTRA_SCSI', 'Ultra SCSI'), ('U160', 'Ultra160'), ('U320', 'Ultra320'), ('SATA_1', 'SATA I (1.5 Gbps)'), ('SATA_2', 'SATA II (3 Gbps)'), ('SATA_3', 'SATA III (6 Gbps)'), ('NVME', 'NVMe (PCIe)'), ('USB', 'USB'), ('FIREWIRE', 'FireWire (IEEE 1394)'), ('OTHER', 'Other')], max_length=50, verbose_name='Interface Name')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
    ]
