# Generated by Django 6.0 on 2025-12-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_gpu_removablestoragedrive_storagedrive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPUs'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'GPU', 'verbose_name_plural': 'GPUs'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM Module', 'verbose_name_plural': 'RAM Modules'},
        ),
        migrations.AlterModelOptions(
            name='removablestoragedrive',
            options={'verbose_name': 'Removable Storage Drive', 'verbose_name_plural': 'Removable Storage Drives'},
        ),
        migrations.AlterModelOptions(
            name='storagedrive',
            options={'verbose_name': 'Storage Drive', 'verbose_name_plural': 'Storage Drives'},
        ),
    ]
