# Generated by Django 6.0 on 2025-12-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_cpu_options_alter_gpu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
