# Generated by Django 6.0 on 2025-12-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_component_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cache_l1_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='L1 Cache (KB)'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache_l2_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='L2 Cache (KB)'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache_l3_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='L3 Cache (KB)'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='tdp_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thermal Design Power (W)'),
        ),
    ]
