# Generated by Django 6.0.1 on 2026-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_cpu_cache_l1_kb_cpu_cache_l2_kb_cpu_cache_l3_kb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AddField(
            model_name='component',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN_BOX', 'Open Box'), ('USED', 'Used'), ('FOR_PARTS', 'For Parts')], default='NEW', max_length=50, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
